services:
  - type: web
    name: my-wordpress-site
    env: php
    buildCommand: "composer install --no-dev"
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: db
        fromDatabase:
          name: my-wordpress-db
          property: host
      - key: 3306
        fromDatabase:
          name: my-wordpress-db
          property: port
      - key: wordpress
        fromDatabase:
          name: my-wordpress-db
          property: user
      - key: wordpress
        fromDatabase:
          name: my-wordpress-db
          property: password
      - key: wordpress
        fromDatabase:
          name: my-wordpress-db
          property: name

databases:
  - name: my-wordpress-db
    type: mysql
    databaseName: mysql
