services:
  - type: web
    name: my-wordpress-site
    dockerfilePath: Dockerfile
    envVars:
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: my-wordpress-db
          property: host
      - key: WORDPRESS_DB_PORT
        fromDatabase:
          name: my-wordpress-db
          property: port
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: my-wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: my-wordpress-db
          property: password
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: my-wordpress-db
          property: database
databases:
  - name: my-wordpress-db
    databaseName: mysql
